ingest_data:
  load_csvs:
    directory: s3://startup-funding-avc/

clean_companies_data:
  filter_columns:
    column_subset: ['permalink', 'name', 'market', 'category_list',
    'funding_total_usd', 'status', 'country_code', 'funding_rounds',
    'founded_at', 'founded_month', 'founded_quarter', 'founded_year',
    'first_funding_at', 'last_funding_at']
    na_subset: ['market']
  generate_onehot_features:
    column: 'status'

clean_rounds_data:
  filter_columns:
    column_subset: ['company_permalink', 'funding_round_type', 'raised_amount_usd']
    na_subset: []
  generate_onehot_features:
    column: 'funding_round_type'

clean_investors_data:
  get_unique_investors:
    all_companies_file: 'data/auxiliary/new_companies_data.csv'

clean_acquisitions_data:
  get_acquisition_count:
    all_companies_file: 'data/auxiliary/new_companies_data.csv'

preprocess_merge_data:
  aggregate_dataframes:
    data_path_list: [
      'data/auxiliary/new_companies_data.csv','data/auxiliary/new_rounds_data.csv',
      'data/auxiliary/new_investors_data.csv','data/auxiliary/new_acquisitions_data.csv',
      'data/auxiliary/new_ipo_data.csv'
      ]
  generate_onehot_features:
    column: 'market'

train_model:
  data_filter:
    selected_features: ['funding_rounds', 'founded_month', 'founded_quarter', 'founded_year', 'country_esp', 'country_ind', 'country_other', 'country_usa', 'days_to_fund', 'months_to_fund', 'days_between_rounds', 'months_between_rounds', 'funding_round_type_debt_financing', 'funding_round_type_post_ipo_debt', 'funding_round_type_post_ipo_equity', 'funding_round_type_private_equity', 'funding_round_type_venture', 'unique_investors', 'median_investor_value', 'no_acquisitions', 'no_ipos', 'market_biotechnology', 'market_clean technology', 'market_enterprise software', 'market_finance', 'market_health and wellness', 'market_hospitality', 'market_internet', 'market_mobile', 'market_other', 'raised_amount_usd_mean']

  fit_model:
    target: 'raised_amount_usd_mean'
    test_size: 0.2
    hyperparams:
      bootstrap: True,
      max_depth: 110
      max_features: 3
      min_samples_leaf: 3
      min_samples_split: 8
      n_estimators: 300
